// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: city/agent/v2/agent_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_city_2fagent_2fv2_2fagent_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_city_2fagent_2fv2_2fagent_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "city/agent/v2/agent.pb.h"
#include "city/agent/v2/motion.pb.h"
#include "city/geo/v2/geo.pb.h"
#include "city/trip/v2/trip.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_city_2fagent_2fv2_2fagent_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_city_2fagent_2fv2_2fagent_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_city_2fagent_2fv2_2fagent_5fservice_2eproto;
namespace city {
namespace agent {
namespace v2 {
class AddAgentRequest;
struct AddAgentRequestDefaultTypeInternal;
extern AddAgentRequestDefaultTypeInternal _AddAgentRequest_default_instance_;
class AddAgentResponse;
struct AddAgentResponseDefaultTypeInternal;
extern AddAgentResponseDefaultTypeInternal _AddAgentResponse_default_instance_;
class GetAgentRequest;
struct GetAgentRequestDefaultTypeInternal;
extern GetAgentRequestDefaultTypeInternal _GetAgentRequest_default_instance_;
class GetAgentResponse;
struct GetAgentResponseDefaultTypeInternal;
extern GetAgentResponseDefaultTypeInternal _GetAgentResponse_default_instance_;
class GetAgentsByLongLatAreaRequest;
struct GetAgentsByLongLatAreaRequestDefaultTypeInternal;
extern GetAgentsByLongLatAreaRequestDefaultTypeInternal _GetAgentsByLongLatAreaRequest_default_instance_;
class GetAgentsByLongLatAreaResponse;
struct GetAgentsByLongLatAreaResponseDefaultTypeInternal;
extern GetAgentsByLongLatAreaResponseDefaultTypeInternal _GetAgentsByLongLatAreaResponse_default_instance_;
class SetScheduleRequest;
struct SetScheduleRequestDefaultTypeInternal;
extern SetScheduleRequestDefaultTypeInternal _SetScheduleRequest_default_instance_;
class SetScheduleResponse;
struct SetScheduleResponseDefaultTypeInternal;
extern SetScheduleResponseDefaultTypeInternal _SetScheduleResponse_default_instance_;
}  // namespace v2
}  // namespace agent
}  // namespace city
PROTOBUF_NAMESPACE_OPEN
template<> ::city::agent::v2::AddAgentRequest* Arena::CreateMaybeMessage<::city::agent::v2::AddAgentRequest>(Arena*);
template<> ::city::agent::v2::AddAgentResponse* Arena::CreateMaybeMessage<::city::agent::v2::AddAgentResponse>(Arena*);
template<> ::city::agent::v2::GetAgentRequest* Arena::CreateMaybeMessage<::city::agent::v2::GetAgentRequest>(Arena*);
template<> ::city::agent::v2::GetAgentResponse* Arena::CreateMaybeMessage<::city::agent::v2::GetAgentResponse>(Arena*);
template<> ::city::agent::v2::GetAgentsByLongLatAreaRequest* Arena::CreateMaybeMessage<::city::agent::v2::GetAgentsByLongLatAreaRequest>(Arena*);
template<> ::city::agent::v2::GetAgentsByLongLatAreaResponse* Arena::CreateMaybeMessage<::city::agent::v2::GetAgentsByLongLatAreaResponse>(Arena*);
template<> ::city::agent::v2::SetScheduleRequest* Arena::CreateMaybeMessage<::city::agent::v2::SetScheduleRequest>(Arena*);
template<> ::city::agent::v2::SetScheduleResponse* Arena::CreateMaybeMessage<::city::agent::v2::SetScheduleResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace city {
namespace agent {
namespace v2 {

// ===================================================================

class GetAgentRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:city.agent.v2.GetAgentRequest) */ {
 public:
  inline GetAgentRequest() : GetAgentRequest(nullptr) {}
  ~GetAgentRequest() override;
  explicit PROTOBUF_CONSTEXPR GetAgentRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetAgentRequest(const GetAgentRequest& from);
  GetAgentRequest(GetAgentRequest&& from) noexcept
    : GetAgentRequest() {
    *this = ::std::move(from);
  }

  inline GetAgentRequest& operator=(const GetAgentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetAgentRequest& operator=(GetAgentRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetAgentRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetAgentRequest* internal_default_instance() {
    return reinterpret_cast<const GetAgentRequest*>(
               &_GetAgentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetAgentRequest& a, GetAgentRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetAgentRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetAgentRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetAgentRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetAgentRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetAgentRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetAgentRequest& from) {
    GetAgentRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetAgentRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.agent.v2.GetAgentRequest";
  }
  protected:
  explicit GetAgentRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAgentIdFieldNumber = 1,
  };
  // int32 agent_id = 1;
  void clear_agent_id();
  int32_t agent_id() const;
  void set_agent_id(int32_t value);
  private:
  int32_t _internal_agent_id() const;
  void _internal_set_agent_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:city.agent.v2.GetAgentRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t agent_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_city_2fagent_2fv2_2fagent_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetAgentResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:city.agent.v2.GetAgentResponse) */ {
 public:
  inline GetAgentResponse() : GetAgentResponse(nullptr) {}
  ~GetAgentResponse() override;
  explicit PROTOBUF_CONSTEXPR GetAgentResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetAgentResponse(const GetAgentResponse& from);
  GetAgentResponse(GetAgentResponse&& from) noexcept
    : GetAgentResponse() {
    *this = ::std::move(from);
  }

  inline GetAgentResponse& operator=(const GetAgentResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetAgentResponse& operator=(GetAgentResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetAgentResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetAgentResponse* internal_default_instance() {
    return reinterpret_cast<const GetAgentResponse*>(
               &_GetAgentResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetAgentResponse& a, GetAgentResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetAgentResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetAgentResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetAgentResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetAgentResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetAgentResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetAgentResponse& from) {
    GetAgentResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetAgentResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.agent.v2.GetAgentResponse";
  }
  protected:
  explicit GetAgentResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBaseFieldNumber = 1,
    kMotionFieldNumber = 2,
  };
  // .city.agent.v2.Agent base = 1;
  bool has_base() const;
  private:
  bool _internal_has_base() const;
  public:
  void clear_base();
  const ::city::agent::v2::Agent& base() const;
  PROTOBUF_NODISCARD ::city::agent::v2::Agent* release_base();
  ::city::agent::v2::Agent* mutable_base();
  void set_allocated_base(::city::agent::v2::Agent* base);
  private:
  const ::city::agent::v2::Agent& _internal_base() const;
  ::city::agent::v2::Agent* _internal_mutable_base();
  public:
  void unsafe_arena_set_allocated_base(
      ::city::agent::v2::Agent* base);
  ::city::agent::v2::Agent* unsafe_arena_release_base();

  // .city.agent.v2.AgentMotion motion = 2;
  bool has_motion() const;
  private:
  bool _internal_has_motion() const;
  public:
  void clear_motion();
  const ::city::agent::v2::AgentMotion& motion() const;
  PROTOBUF_NODISCARD ::city::agent::v2::AgentMotion* release_motion();
  ::city::agent::v2::AgentMotion* mutable_motion();
  void set_allocated_motion(::city::agent::v2::AgentMotion* motion);
  private:
  const ::city::agent::v2::AgentMotion& _internal_motion() const;
  ::city::agent::v2::AgentMotion* _internal_mutable_motion();
  public:
  void unsafe_arena_set_allocated_motion(
      ::city::agent::v2::AgentMotion* motion);
  ::city::agent::v2::AgentMotion* unsafe_arena_release_motion();

  // @@protoc_insertion_point(class_scope:city.agent.v2.GetAgentResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::city::agent::v2::Agent* base_;
    ::city::agent::v2::AgentMotion* motion_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_city_2fagent_2fv2_2fagent_5fservice_2eproto;
};
// -------------------------------------------------------------------

class AddAgentRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:city.agent.v2.AddAgentRequest) */ {
 public:
  inline AddAgentRequest() : AddAgentRequest(nullptr) {}
  ~AddAgentRequest() override;
  explicit PROTOBUF_CONSTEXPR AddAgentRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddAgentRequest(const AddAgentRequest& from);
  AddAgentRequest(AddAgentRequest&& from) noexcept
    : AddAgentRequest() {
    *this = ::std::move(from);
  }

  inline AddAgentRequest& operator=(const AddAgentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddAgentRequest& operator=(AddAgentRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddAgentRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddAgentRequest* internal_default_instance() {
    return reinterpret_cast<const AddAgentRequest*>(
               &_AddAgentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AddAgentRequest& a, AddAgentRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AddAgentRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddAgentRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddAgentRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddAgentRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddAgentRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddAgentRequest& from) {
    AddAgentRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddAgentRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.agent.v2.AddAgentRequest";
  }
  protected:
  explicit AddAgentRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAgentFieldNumber = 1,
  };
  // .city.agent.v2.Agent agent = 1;
  bool has_agent() const;
  private:
  bool _internal_has_agent() const;
  public:
  void clear_agent();
  const ::city::agent::v2::Agent& agent() const;
  PROTOBUF_NODISCARD ::city::agent::v2::Agent* release_agent();
  ::city::agent::v2::Agent* mutable_agent();
  void set_allocated_agent(::city::agent::v2::Agent* agent);
  private:
  const ::city::agent::v2::Agent& _internal_agent() const;
  ::city::agent::v2::Agent* _internal_mutable_agent();
  public:
  void unsafe_arena_set_allocated_agent(
      ::city::agent::v2::Agent* agent);
  ::city::agent::v2::Agent* unsafe_arena_release_agent();

  // @@protoc_insertion_point(class_scope:city.agent.v2.AddAgentRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::city::agent::v2::Agent* agent_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_city_2fagent_2fv2_2fagent_5fservice_2eproto;
};
// -------------------------------------------------------------------

class AddAgentResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:city.agent.v2.AddAgentResponse) */ {
 public:
  inline AddAgentResponse() : AddAgentResponse(nullptr) {}
  ~AddAgentResponse() override;
  explicit PROTOBUF_CONSTEXPR AddAgentResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddAgentResponse(const AddAgentResponse& from);
  AddAgentResponse(AddAgentResponse&& from) noexcept
    : AddAgentResponse() {
    *this = ::std::move(from);
  }

  inline AddAgentResponse& operator=(const AddAgentResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddAgentResponse& operator=(AddAgentResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddAgentResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddAgentResponse* internal_default_instance() {
    return reinterpret_cast<const AddAgentResponse*>(
               &_AddAgentResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(AddAgentResponse& a, AddAgentResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AddAgentResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddAgentResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddAgentResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddAgentResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddAgentResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddAgentResponse& from) {
    AddAgentResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddAgentResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.agent.v2.AddAgentResponse";
  }
  protected:
  explicit AddAgentResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAgentIdFieldNumber = 1,
  };
  // int32 agent_id = 1;
  void clear_agent_id();
  int32_t agent_id() const;
  void set_agent_id(int32_t value);
  private:
  int32_t _internal_agent_id() const;
  void _internal_set_agent_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:city.agent.v2.AddAgentResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t agent_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_city_2fagent_2fv2_2fagent_5fservice_2eproto;
};
// -------------------------------------------------------------------

class SetScheduleRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:city.agent.v2.SetScheduleRequest) */ {
 public:
  inline SetScheduleRequest() : SetScheduleRequest(nullptr) {}
  ~SetScheduleRequest() override;
  explicit PROTOBUF_CONSTEXPR SetScheduleRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SetScheduleRequest(const SetScheduleRequest& from);
  SetScheduleRequest(SetScheduleRequest&& from) noexcept
    : SetScheduleRequest() {
    *this = ::std::move(from);
  }

  inline SetScheduleRequest& operator=(const SetScheduleRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetScheduleRequest& operator=(SetScheduleRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetScheduleRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetScheduleRequest* internal_default_instance() {
    return reinterpret_cast<const SetScheduleRequest*>(
               &_SetScheduleRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SetScheduleRequest& a, SetScheduleRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SetScheduleRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetScheduleRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetScheduleRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SetScheduleRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SetScheduleRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SetScheduleRequest& from) {
    SetScheduleRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetScheduleRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.agent.v2.SetScheduleRequest";
  }
  protected:
  explicit SetScheduleRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSchedulesFieldNumber = 2,
    kAgentIdFieldNumber = 1,
  };
  // repeated .city.trip.v2.Schedule schedules = 2;
  int schedules_size() const;
  private:
  int _internal_schedules_size() const;
  public:
  void clear_schedules();
  ::city::trip::v2::Schedule* mutable_schedules(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::trip::v2::Schedule >*
      mutable_schedules();
  private:
  const ::city::trip::v2::Schedule& _internal_schedules(int index) const;
  ::city::trip::v2::Schedule* _internal_add_schedules();
  public:
  const ::city::trip::v2::Schedule& schedules(int index) const;
  ::city::trip::v2::Schedule* add_schedules();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::trip::v2::Schedule >&
      schedules() const;

  // int32 agent_id = 1;
  void clear_agent_id();
  int32_t agent_id() const;
  void set_agent_id(int32_t value);
  private:
  int32_t _internal_agent_id() const;
  void _internal_set_agent_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:city.agent.v2.SetScheduleRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::trip::v2::Schedule > schedules_;
    int32_t agent_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_city_2fagent_2fv2_2fagent_5fservice_2eproto;
};
// -------------------------------------------------------------------

class SetScheduleResponse final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:city.agent.v2.SetScheduleResponse) */ {
 public:
  inline SetScheduleResponse() : SetScheduleResponse(nullptr) {}
  explicit PROTOBUF_CONSTEXPR SetScheduleResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SetScheduleResponse(const SetScheduleResponse& from);
  SetScheduleResponse(SetScheduleResponse&& from) noexcept
    : SetScheduleResponse() {
    *this = ::std::move(from);
  }

  inline SetScheduleResponse& operator=(const SetScheduleResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetScheduleResponse& operator=(SetScheduleResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetScheduleResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetScheduleResponse* internal_default_instance() {
    return reinterpret_cast<const SetScheduleResponse*>(
               &_SetScheduleResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(SetScheduleResponse& a, SetScheduleResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SetScheduleResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetScheduleResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetScheduleResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SetScheduleResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const SetScheduleResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const SetScheduleResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.agent.v2.SetScheduleResponse";
  }
  protected:
  explicit SetScheduleResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:city.agent.v2.SetScheduleResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_city_2fagent_2fv2_2fagent_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetAgentsByLongLatAreaRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:city.agent.v2.GetAgentsByLongLatAreaRequest) */ {
 public:
  inline GetAgentsByLongLatAreaRequest() : GetAgentsByLongLatAreaRequest(nullptr) {}
  ~GetAgentsByLongLatAreaRequest() override;
  explicit PROTOBUF_CONSTEXPR GetAgentsByLongLatAreaRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetAgentsByLongLatAreaRequest(const GetAgentsByLongLatAreaRequest& from);
  GetAgentsByLongLatAreaRequest(GetAgentsByLongLatAreaRequest&& from) noexcept
    : GetAgentsByLongLatAreaRequest() {
    *this = ::std::move(from);
  }

  inline GetAgentsByLongLatAreaRequest& operator=(const GetAgentsByLongLatAreaRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetAgentsByLongLatAreaRequest& operator=(GetAgentsByLongLatAreaRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetAgentsByLongLatAreaRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetAgentsByLongLatAreaRequest* internal_default_instance() {
    return reinterpret_cast<const GetAgentsByLongLatAreaRequest*>(
               &_GetAgentsByLongLatAreaRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(GetAgentsByLongLatAreaRequest& a, GetAgentsByLongLatAreaRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetAgentsByLongLatAreaRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetAgentsByLongLatAreaRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetAgentsByLongLatAreaRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetAgentsByLongLatAreaRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetAgentsByLongLatAreaRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetAgentsByLongLatAreaRequest& from) {
    GetAgentsByLongLatAreaRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetAgentsByLongLatAreaRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.agent.v2.GetAgentsByLongLatAreaRequest";
  }
  protected:
  explicit GetAgentsByLongLatAreaRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAreaFieldNumber = 1,
  };
  // .city.geo.v2.LongLatBBox area = 1;
  bool has_area() const;
  private:
  bool _internal_has_area() const;
  public:
  void clear_area();
  const ::city::geo::v2::LongLatBBox& area() const;
  PROTOBUF_NODISCARD ::city::geo::v2::LongLatBBox* release_area();
  ::city::geo::v2::LongLatBBox* mutable_area();
  void set_allocated_area(::city::geo::v2::LongLatBBox* area);
  private:
  const ::city::geo::v2::LongLatBBox& _internal_area() const;
  ::city::geo::v2::LongLatBBox* _internal_mutable_area();
  public:
  void unsafe_arena_set_allocated_area(
      ::city::geo::v2::LongLatBBox* area);
  ::city::geo::v2::LongLatBBox* unsafe_arena_release_area();

  // @@protoc_insertion_point(class_scope:city.agent.v2.GetAgentsByLongLatAreaRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::city::geo::v2::LongLatBBox* area_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_city_2fagent_2fv2_2fagent_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetAgentsByLongLatAreaResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:city.agent.v2.GetAgentsByLongLatAreaResponse) */ {
 public:
  inline GetAgentsByLongLatAreaResponse() : GetAgentsByLongLatAreaResponse(nullptr) {}
  ~GetAgentsByLongLatAreaResponse() override;
  explicit PROTOBUF_CONSTEXPR GetAgentsByLongLatAreaResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetAgentsByLongLatAreaResponse(const GetAgentsByLongLatAreaResponse& from);
  GetAgentsByLongLatAreaResponse(GetAgentsByLongLatAreaResponse&& from) noexcept
    : GetAgentsByLongLatAreaResponse() {
    *this = ::std::move(from);
  }

  inline GetAgentsByLongLatAreaResponse& operator=(const GetAgentsByLongLatAreaResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetAgentsByLongLatAreaResponse& operator=(GetAgentsByLongLatAreaResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetAgentsByLongLatAreaResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetAgentsByLongLatAreaResponse* internal_default_instance() {
    return reinterpret_cast<const GetAgentsByLongLatAreaResponse*>(
               &_GetAgentsByLongLatAreaResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(GetAgentsByLongLatAreaResponse& a, GetAgentsByLongLatAreaResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetAgentsByLongLatAreaResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetAgentsByLongLatAreaResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetAgentsByLongLatAreaResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetAgentsByLongLatAreaResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetAgentsByLongLatAreaResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetAgentsByLongLatAreaResponse& from) {
    GetAgentsByLongLatAreaResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetAgentsByLongLatAreaResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.agent.v2.GetAgentsByLongLatAreaResponse";
  }
  protected:
  explicit GetAgentsByLongLatAreaResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMotionsFieldNumber = 2,
    kStepFieldNumber = 1,
  };
  // repeated .city.agent.v2.AgentMotion motions = 2;
  int motions_size() const;
  private:
  int _internal_motions_size() const;
  public:
  void clear_motions();
  ::city::agent::v2::AgentMotion* mutable_motions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::agent::v2::AgentMotion >*
      mutable_motions();
  private:
  const ::city::agent::v2::AgentMotion& _internal_motions(int index) const;
  ::city::agent::v2::AgentMotion* _internal_add_motions();
  public:
  const ::city::agent::v2::AgentMotion& motions(int index) const;
  ::city::agent::v2::AgentMotion* add_motions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::agent::v2::AgentMotion >&
      motions() const;

  // int32 step = 1;
  void clear_step();
  int32_t step() const;
  void set_step(int32_t value);
  private:
  int32_t _internal_step() const;
  void _internal_set_step(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:city.agent.v2.GetAgentsByLongLatAreaResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::agent::v2::AgentMotion > motions_;
    int32_t step_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_city_2fagent_2fv2_2fagent_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetAgentRequest

// int32 agent_id = 1;
inline void GetAgentRequest::clear_agent_id() {
  _impl_.agent_id_ = 0;
}
inline int32_t GetAgentRequest::_internal_agent_id() const {
  return _impl_.agent_id_;
}
inline int32_t GetAgentRequest::agent_id() const {
  // @@protoc_insertion_point(field_get:city.agent.v2.GetAgentRequest.agent_id)
  return _internal_agent_id();
}
inline void GetAgentRequest::_internal_set_agent_id(int32_t value) {
  
  _impl_.agent_id_ = value;
}
inline void GetAgentRequest::set_agent_id(int32_t value) {
  _internal_set_agent_id(value);
  // @@protoc_insertion_point(field_set:city.agent.v2.GetAgentRequest.agent_id)
}

// -------------------------------------------------------------------

// GetAgentResponse

// .city.agent.v2.Agent base = 1;
inline bool GetAgentResponse::_internal_has_base() const {
  return this != internal_default_instance() && _impl_.base_ != nullptr;
}
inline bool GetAgentResponse::has_base() const {
  return _internal_has_base();
}
inline const ::city::agent::v2::Agent& GetAgentResponse::_internal_base() const {
  const ::city::agent::v2::Agent* p = _impl_.base_;
  return p != nullptr ? *p : reinterpret_cast<const ::city::agent::v2::Agent&>(
      ::city::agent::v2::_Agent_default_instance_);
}
inline const ::city::agent::v2::Agent& GetAgentResponse::base() const {
  // @@protoc_insertion_point(field_get:city.agent.v2.GetAgentResponse.base)
  return _internal_base();
}
inline void GetAgentResponse::unsafe_arena_set_allocated_base(
    ::city::agent::v2::Agent* base) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.base_);
  }
  _impl_.base_ = base;
  if (base) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:city.agent.v2.GetAgentResponse.base)
}
inline ::city::agent::v2::Agent* GetAgentResponse::release_base() {
  
  ::city::agent::v2::Agent* temp = _impl_.base_;
  _impl_.base_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::city::agent::v2::Agent* GetAgentResponse::unsafe_arena_release_base() {
  // @@protoc_insertion_point(field_release:city.agent.v2.GetAgentResponse.base)
  
  ::city::agent::v2::Agent* temp = _impl_.base_;
  _impl_.base_ = nullptr;
  return temp;
}
inline ::city::agent::v2::Agent* GetAgentResponse::_internal_mutable_base() {
  
  if (_impl_.base_ == nullptr) {
    auto* p = CreateMaybeMessage<::city::agent::v2::Agent>(GetArenaForAllocation());
    _impl_.base_ = p;
  }
  return _impl_.base_;
}
inline ::city::agent::v2::Agent* GetAgentResponse::mutable_base() {
  ::city::agent::v2::Agent* _msg = _internal_mutable_base();
  // @@protoc_insertion_point(field_mutable:city.agent.v2.GetAgentResponse.base)
  return _msg;
}
inline void GetAgentResponse::set_allocated_base(::city::agent::v2::Agent* base) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.base_);
  }
  if (base) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(base));
    if (message_arena != submessage_arena) {
      base = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, base, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.base_ = base;
  // @@protoc_insertion_point(field_set_allocated:city.agent.v2.GetAgentResponse.base)
}

// .city.agent.v2.AgentMotion motion = 2;
inline bool GetAgentResponse::_internal_has_motion() const {
  return this != internal_default_instance() && _impl_.motion_ != nullptr;
}
inline bool GetAgentResponse::has_motion() const {
  return _internal_has_motion();
}
inline const ::city::agent::v2::AgentMotion& GetAgentResponse::_internal_motion() const {
  const ::city::agent::v2::AgentMotion* p = _impl_.motion_;
  return p != nullptr ? *p : reinterpret_cast<const ::city::agent::v2::AgentMotion&>(
      ::city::agent::v2::_AgentMotion_default_instance_);
}
inline const ::city::agent::v2::AgentMotion& GetAgentResponse::motion() const {
  // @@protoc_insertion_point(field_get:city.agent.v2.GetAgentResponse.motion)
  return _internal_motion();
}
inline void GetAgentResponse::unsafe_arena_set_allocated_motion(
    ::city::agent::v2::AgentMotion* motion) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.motion_);
  }
  _impl_.motion_ = motion;
  if (motion) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:city.agent.v2.GetAgentResponse.motion)
}
inline ::city::agent::v2::AgentMotion* GetAgentResponse::release_motion() {
  
  ::city::agent::v2::AgentMotion* temp = _impl_.motion_;
  _impl_.motion_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::city::agent::v2::AgentMotion* GetAgentResponse::unsafe_arena_release_motion() {
  // @@protoc_insertion_point(field_release:city.agent.v2.GetAgentResponse.motion)
  
  ::city::agent::v2::AgentMotion* temp = _impl_.motion_;
  _impl_.motion_ = nullptr;
  return temp;
}
inline ::city::agent::v2::AgentMotion* GetAgentResponse::_internal_mutable_motion() {
  
  if (_impl_.motion_ == nullptr) {
    auto* p = CreateMaybeMessage<::city::agent::v2::AgentMotion>(GetArenaForAllocation());
    _impl_.motion_ = p;
  }
  return _impl_.motion_;
}
inline ::city::agent::v2::AgentMotion* GetAgentResponse::mutable_motion() {
  ::city::agent::v2::AgentMotion* _msg = _internal_mutable_motion();
  // @@protoc_insertion_point(field_mutable:city.agent.v2.GetAgentResponse.motion)
  return _msg;
}
inline void GetAgentResponse::set_allocated_motion(::city::agent::v2::AgentMotion* motion) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.motion_);
  }
  if (motion) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(motion));
    if (message_arena != submessage_arena) {
      motion = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, motion, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.motion_ = motion;
  // @@protoc_insertion_point(field_set_allocated:city.agent.v2.GetAgentResponse.motion)
}

// -------------------------------------------------------------------

// AddAgentRequest

// .city.agent.v2.Agent agent = 1;
inline bool AddAgentRequest::_internal_has_agent() const {
  return this != internal_default_instance() && _impl_.agent_ != nullptr;
}
inline bool AddAgentRequest::has_agent() const {
  return _internal_has_agent();
}
inline const ::city::agent::v2::Agent& AddAgentRequest::_internal_agent() const {
  const ::city::agent::v2::Agent* p = _impl_.agent_;
  return p != nullptr ? *p : reinterpret_cast<const ::city::agent::v2::Agent&>(
      ::city::agent::v2::_Agent_default_instance_);
}
inline const ::city::agent::v2::Agent& AddAgentRequest::agent() const {
  // @@protoc_insertion_point(field_get:city.agent.v2.AddAgentRequest.agent)
  return _internal_agent();
}
inline void AddAgentRequest::unsafe_arena_set_allocated_agent(
    ::city::agent::v2::Agent* agent) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.agent_);
  }
  _impl_.agent_ = agent;
  if (agent) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:city.agent.v2.AddAgentRequest.agent)
}
inline ::city::agent::v2::Agent* AddAgentRequest::release_agent() {
  
  ::city::agent::v2::Agent* temp = _impl_.agent_;
  _impl_.agent_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::city::agent::v2::Agent* AddAgentRequest::unsafe_arena_release_agent() {
  // @@protoc_insertion_point(field_release:city.agent.v2.AddAgentRequest.agent)
  
  ::city::agent::v2::Agent* temp = _impl_.agent_;
  _impl_.agent_ = nullptr;
  return temp;
}
inline ::city::agent::v2::Agent* AddAgentRequest::_internal_mutable_agent() {
  
  if (_impl_.agent_ == nullptr) {
    auto* p = CreateMaybeMessage<::city::agent::v2::Agent>(GetArenaForAllocation());
    _impl_.agent_ = p;
  }
  return _impl_.agent_;
}
inline ::city::agent::v2::Agent* AddAgentRequest::mutable_agent() {
  ::city::agent::v2::Agent* _msg = _internal_mutable_agent();
  // @@protoc_insertion_point(field_mutable:city.agent.v2.AddAgentRequest.agent)
  return _msg;
}
inline void AddAgentRequest::set_allocated_agent(::city::agent::v2::Agent* agent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.agent_);
  }
  if (agent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(agent));
    if (message_arena != submessage_arena) {
      agent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, agent, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.agent_ = agent;
  // @@protoc_insertion_point(field_set_allocated:city.agent.v2.AddAgentRequest.agent)
}

// -------------------------------------------------------------------

// AddAgentResponse

// int32 agent_id = 1;
inline void AddAgentResponse::clear_agent_id() {
  _impl_.agent_id_ = 0;
}
inline int32_t AddAgentResponse::_internal_agent_id() const {
  return _impl_.agent_id_;
}
inline int32_t AddAgentResponse::agent_id() const {
  // @@protoc_insertion_point(field_get:city.agent.v2.AddAgentResponse.agent_id)
  return _internal_agent_id();
}
inline void AddAgentResponse::_internal_set_agent_id(int32_t value) {
  
  _impl_.agent_id_ = value;
}
inline void AddAgentResponse::set_agent_id(int32_t value) {
  _internal_set_agent_id(value);
  // @@protoc_insertion_point(field_set:city.agent.v2.AddAgentResponse.agent_id)
}

// -------------------------------------------------------------------

// SetScheduleRequest

// int32 agent_id = 1;
inline void SetScheduleRequest::clear_agent_id() {
  _impl_.agent_id_ = 0;
}
inline int32_t SetScheduleRequest::_internal_agent_id() const {
  return _impl_.agent_id_;
}
inline int32_t SetScheduleRequest::agent_id() const {
  // @@protoc_insertion_point(field_get:city.agent.v2.SetScheduleRequest.agent_id)
  return _internal_agent_id();
}
inline void SetScheduleRequest::_internal_set_agent_id(int32_t value) {
  
  _impl_.agent_id_ = value;
}
inline void SetScheduleRequest::set_agent_id(int32_t value) {
  _internal_set_agent_id(value);
  // @@protoc_insertion_point(field_set:city.agent.v2.SetScheduleRequest.agent_id)
}

// repeated .city.trip.v2.Schedule schedules = 2;
inline int SetScheduleRequest::_internal_schedules_size() const {
  return _impl_.schedules_.size();
}
inline int SetScheduleRequest::schedules_size() const {
  return _internal_schedules_size();
}
inline ::city::trip::v2::Schedule* SetScheduleRequest::mutable_schedules(int index) {
  // @@protoc_insertion_point(field_mutable:city.agent.v2.SetScheduleRequest.schedules)
  return _impl_.schedules_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::trip::v2::Schedule >*
SetScheduleRequest::mutable_schedules() {
  // @@protoc_insertion_point(field_mutable_list:city.agent.v2.SetScheduleRequest.schedules)
  return &_impl_.schedules_;
}
inline const ::city::trip::v2::Schedule& SetScheduleRequest::_internal_schedules(int index) const {
  return _impl_.schedules_.Get(index);
}
inline const ::city::trip::v2::Schedule& SetScheduleRequest::schedules(int index) const {
  // @@protoc_insertion_point(field_get:city.agent.v2.SetScheduleRequest.schedules)
  return _internal_schedules(index);
}
inline ::city::trip::v2::Schedule* SetScheduleRequest::_internal_add_schedules() {
  return _impl_.schedules_.Add();
}
inline ::city::trip::v2::Schedule* SetScheduleRequest::add_schedules() {
  ::city::trip::v2::Schedule* _add = _internal_add_schedules();
  // @@protoc_insertion_point(field_add:city.agent.v2.SetScheduleRequest.schedules)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::trip::v2::Schedule >&
SetScheduleRequest::schedules() const {
  // @@protoc_insertion_point(field_list:city.agent.v2.SetScheduleRequest.schedules)
  return _impl_.schedules_;
}

// -------------------------------------------------------------------

// SetScheduleResponse

// -------------------------------------------------------------------

// GetAgentsByLongLatAreaRequest

// .city.geo.v2.LongLatBBox area = 1;
inline bool GetAgentsByLongLatAreaRequest::_internal_has_area() const {
  return this != internal_default_instance() && _impl_.area_ != nullptr;
}
inline bool GetAgentsByLongLatAreaRequest::has_area() const {
  return _internal_has_area();
}
inline const ::city::geo::v2::LongLatBBox& GetAgentsByLongLatAreaRequest::_internal_area() const {
  const ::city::geo::v2::LongLatBBox* p = _impl_.area_;
  return p != nullptr ? *p : reinterpret_cast<const ::city::geo::v2::LongLatBBox&>(
      ::city::geo::v2::_LongLatBBox_default_instance_);
}
inline const ::city::geo::v2::LongLatBBox& GetAgentsByLongLatAreaRequest::area() const {
  // @@protoc_insertion_point(field_get:city.agent.v2.GetAgentsByLongLatAreaRequest.area)
  return _internal_area();
}
inline void GetAgentsByLongLatAreaRequest::unsafe_arena_set_allocated_area(
    ::city::geo::v2::LongLatBBox* area) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.area_);
  }
  _impl_.area_ = area;
  if (area) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:city.agent.v2.GetAgentsByLongLatAreaRequest.area)
}
inline ::city::geo::v2::LongLatBBox* GetAgentsByLongLatAreaRequest::release_area() {
  
  ::city::geo::v2::LongLatBBox* temp = _impl_.area_;
  _impl_.area_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::city::geo::v2::LongLatBBox* GetAgentsByLongLatAreaRequest::unsafe_arena_release_area() {
  // @@protoc_insertion_point(field_release:city.agent.v2.GetAgentsByLongLatAreaRequest.area)
  
  ::city::geo::v2::LongLatBBox* temp = _impl_.area_;
  _impl_.area_ = nullptr;
  return temp;
}
inline ::city::geo::v2::LongLatBBox* GetAgentsByLongLatAreaRequest::_internal_mutable_area() {
  
  if (_impl_.area_ == nullptr) {
    auto* p = CreateMaybeMessage<::city::geo::v2::LongLatBBox>(GetArenaForAllocation());
    _impl_.area_ = p;
  }
  return _impl_.area_;
}
inline ::city::geo::v2::LongLatBBox* GetAgentsByLongLatAreaRequest::mutable_area() {
  ::city::geo::v2::LongLatBBox* _msg = _internal_mutable_area();
  // @@protoc_insertion_point(field_mutable:city.agent.v2.GetAgentsByLongLatAreaRequest.area)
  return _msg;
}
inline void GetAgentsByLongLatAreaRequest::set_allocated_area(::city::geo::v2::LongLatBBox* area) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.area_);
  }
  if (area) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(area));
    if (message_arena != submessage_arena) {
      area = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, area, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.area_ = area;
  // @@protoc_insertion_point(field_set_allocated:city.agent.v2.GetAgentsByLongLatAreaRequest.area)
}

// -------------------------------------------------------------------

// GetAgentsByLongLatAreaResponse

// int32 step = 1;
inline void GetAgentsByLongLatAreaResponse::clear_step() {
  _impl_.step_ = 0;
}
inline int32_t GetAgentsByLongLatAreaResponse::_internal_step() const {
  return _impl_.step_;
}
inline int32_t GetAgentsByLongLatAreaResponse::step() const {
  // @@protoc_insertion_point(field_get:city.agent.v2.GetAgentsByLongLatAreaResponse.step)
  return _internal_step();
}
inline void GetAgentsByLongLatAreaResponse::_internal_set_step(int32_t value) {
  
  _impl_.step_ = value;
}
inline void GetAgentsByLongLatAreaResponse::set_step(int32_t value) {
  _internal_set_step(value);
  // @@protoc_insertion_point(field_set:city.agent.v2.GetAgentsByLongLatAreaResponse.step)
}

// repeated .city.agent.v2.AgentMotion motions = 2;
inline int GetAgentsByLongLatAreaResponse::_internal_motions_size() const {
  return _impl_.motions_.size();
}
inline int GetAgentsByLongLatAreaResponse::motions_size() const {
  return _internal_motions_size();
}
inline ::city::agent::v2::AgentMotion* GetAgentsByLongLatAreaResponse::mutable_motions(int index) {
  // @@protoc_insertion_point(field_mutable:city.agent.v2.GetAgentsByLongLatAreaResponse.motions)
  return _impl_.motions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::agent::v2::AgentMotion >*
GetAgentsByLongLatAreaResponse::mutable_motions() {
  // @@protoc_insertion_point(field_mutable_list:city.agent.v2.GetAgentsByLongLatAreaResponse.motions)
  return &_impl_.motions_;
}
inline const ::city::agent::v2::AgentMotion& GetAgentsByLongLatAreaResponse::_internal_motions(int index) const {
  return _impl_.motions_.Get(index);
}
inline const ::city::agent::v2::AgentMotion& GetAgentsByLongLatAreaResponse::motions(int index) const {
  // @@protoc_insertion_point(field_get:city.agent.v2.GetAgentsByLongLatAreaResponse.motions)
  return _internal_motions(index);
}
inline ::city::agent::v2::AgentMotion* GetAgentsByLongLatAreaResponse::_internal_add_motions() {
  return _impl_.motions_.Add();
}
inline ::city::agent::v2::AgentMotion* GetAgentsByLongLatAreaResponse::add_motions() {
  ::city::agent::v2::AgentMotion* _add = _internal_add_motions();
  // @@protoc_insertion_point(field_add:city.agent.v2.GetAgentsByLongLatAreaResponse.motions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::agent::v2::AgentMotion >&
GetAgentsByLongLatAreaResponse::motions() const {
  // @@protoc_insertion_point(field_list:city.agent.v2.GetAgentsByLongLatAreaResponse.motions)
  return _impl_.motions_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v2
}  // namespace agent
}  // namespace city

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_city_2fagent_2fv2_2fagent_5fservice_2eproto
