variables:
  # https://setuptools-git-versioning.readthedocs.io/en/stable/ci.html
  GIT_DEPTH: 0
  VERSION_REGEX: /^v\d+\.\d+\.\d+.*$/

stages:
  - build

build-docker-image:
  # default image of runner with tag dind
  # image: docker:dind
  tags:
    - dind
  stage: build
  only:
    - main
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    # tag格式: <sha1>-<time>
    - export TIME=$(date +%s)
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${TIME} -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${TIME}
    - docker push ${CI_REGISTRY_IMAGE}:latest
