// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: city/event/v2/event_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_city_2fevent_2fv2_2fevent_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_city_2fevent_2fv2_2fevent_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "city/event/v2/event.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_city_2fevent_2fv2_2fevent_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_city_2fevent_2fv2_2fevent_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_city_2fevent_2fv2_2fevent_5fservice_2eproto;
namespace city {
namespace event {
namespace v2 {
class GetEventsByTopicRequest;
struct GetEventsByTopicRequestDefaultTypeInternal;
extern GetEventsByTopicRequestDefaultTypeInternal _GetEventsByTopicRequest_default_instance_;
class GetEventsByTopicResponse;
struct GetEventsByTopicResponseDefaultTypeInternal;
extern GetEventsByTopicResponseDefaultTypeInternal _GetEventsByTopicResponse_default_instance_;
class ResolveEventsRequest;
struct ResolveEventsRequestDefaultTypeInternal;
extern ResolveEventsRequestDefaultTypeInternal _ResolveEventsRequest_default_instance_;
class ResolveEventsResponse;
struct ResolveEventsResponseDefaultTypeInternal;
extern ResolveEventsResponseDefaultTypeInternal _ResolveEventsResponse_default_instance_;
}  // namespace v2
}  // namespace event
}  // namespace city
PROTOBUF_NAMESPACE_OPEN
template<> ::city::event::v2::GetEventsByTopicRequest* Arena::CreateMaybeMessage<::city::event::v2::GetEventsByTopicRequest>(Arena*);
template<> ::city::event::v2::GetEventsByTopicResponse* Arena::CreateMaybeMessage<::city::event::v2::GetEventsByTopicResponse>(Arena*);
template<> ::city::event::v2::ResolveEventsRequest* Arena::CreateMaybeMessage<::city::event::v2::ResolveEventsRequest>(Arena*);
template<> ::city::event::v2::ResolveEventsResponse* Arena::CreateMaybeMessage<::city::event::v2::ResolveEventsResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace city {
namespace event {
namespace v2 {

// ===================================================================

class GetEventsByTopicRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:city.event.v2.GetEventsByTopicRequest) */ {
 public:
  inline GetEventsByTopicRequest() : GetEventsByTopicRequest(nullptr) {}
  ~GetEventsByTopicRequest() override;
  explicit PROTOBUF_CONSTEXPR GetEventsByTopicRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetEventsByTopicRequest(const GetEventsByTopicRequest& from);
  GetEventsByTopicRequest(GetEventsByTopicRequest&& from) noexcept
    : GetEventsByTopicRequest() {
    *this = ::std::move(from);
  }

  inline GetEventsByTopicRequest& operator=(const GetEventsByTopicRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetEventsByTopicRequest& operator=(GetEventsByTopicRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetEventsByTopicRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetEventsByTopicRequest* internal_default_instance() {
    return reinterpret_cast<const GetEventsByTopicRequest*>(
               &_GetEventsByTopicRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetEventsByTopicRequest& a, GetEventsByTopicRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetEventsByTopicRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetEventsByTopicRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetEventsByTopicRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetEventsByTopicRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetEventsByTopicRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetEventsByTopicRequest& from) {
    GetEventsByTopicRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetEventsByTopicRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.event.v2.GetEventsByTopicRequest";
  }
  protected:
  explicit GetEventsByTopicRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTopicFieldNumber = 1,
  };
  // string topic = 1;
  void clear_topic();
  const std::string& topic() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_topic(ArgT0&& arg0, ArgT... args);
  std::string* mutable_topic();
  PROTOBUF_NODISCARD std::string* release_topic();
  void set_allocated_topic(std::string* topic);
  private:
  const std::string& _internal_topic() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_topic(const std::string& value);
  std::string* _internal_mutable_topic();
  public:

  // @@protoc_insertion_point(class_scope:city.event.v2.GetEventsByTopicRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr topic_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_city_2fevent_2fv2_2fevent_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetEventsByTopicResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:city.event.v2.GetEventsByTopicResponse) */ {
 public:
  inline GetEventsByTopicResponse() : GetEventsByTopicResponse(nullptr) {}
  ~GetEventsByTopicResponse() override;
  explicit PROTOBUF_CONSTEXPR GetEventsByTopicResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetEventsByTopicResponse(const GetEventsByTopicResponse& from);
  GetEventsByTopicResponse(GetEventsByTopicResponse&& from) noexcept
    : GetEventsByTopicResponse() {
    *this = ::std::move(from);
  }

  inline GetEventsByTopicResponse& operator=(const GetEventsByTopicResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetEventsByTopicResponse& operator=(GetEventsByTopicResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetEventsByTopicResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetEventsByTopicResponse* internal_default_instance() {
    return reinterpret_cast<const GetEventsByTopicResponse*>(
               &_GetEventsByTopicResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetEventsByTopicResponse& a, GetEventsByTopicResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetEventsByTopicResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetEventsByTopicResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetEventsByTopicResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetEventsByTopicResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetEventsByTopicResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetEventsByTopicResponse& from) {
    GetEventsByTopicResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetEventsByTopicResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.event.v2.GetEventsByTopicResponse";
  }
  protected:
  explicit GetEventsByTopicResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEventsFieldNumber = 1,
  };
  // repeated .city.event.v2.Event events = 1;
  int events_size() const;
  private:
  int _internal_events_size() const;
  public:
  void clear_events();
  ::city::event::v2::Event* mutable_events(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::event::v2::Event >*
      mutable_events();
  private:
  const ::city::event::v2::Event& _internal_events(int index) const;
  ::city::event::v2::Event* _internal_add_events();
  public:
  const ::city::event::v2::Event& events(int index) const;
  ::city::event::v2::Event* add_events();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::event::v2::Event >&
      events() const;

  // @@protoc_insertion_point(class_scope:city.event.v2.GetEventsByTopicResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::event::v2::Event > events_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_city_2fevent_2fv2_2fevent_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ResolveEventsRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:city.event.v2.ResolveEventsRequest) */ {
 public:
  inline ResolveEventsRequest() : ResolveEventsRequest(nullptr) {}
  ~ResolveEventsRequest() override;
  explicit PROTOBUF_CONSTEXPR ResolveEventsRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResolveEventsRequest(const ResolveEventsRequest& from);
  ResolveEventsRequest(ResolveEventsRequest&& from) noexcept
    : ResolveEventsRequest() {
    *this = ::std::move(from);
  }

  inline ResolveEventsRequest& operator=(const ResolveEventsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResolveEventsRequest& operator=(ResolveEventsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResolveEventsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResolveEventsRequest* internal_default_instance() {
    return reinterpret_cast<const ResolveEventsRequest*>(
               &_ResolveEventsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ResolveEventsRequest& a, ResolveEventsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ResolveEventsRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResolveEventsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResolveEventsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResolveEventsRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ResolveEventsRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ResolveEventsRequest& from) {
    ResolveEventsRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResolveEventsRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.event.v2.ResolveEventsRequest";
  }
  protected:
  explicit ResolveEventsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEventsFieldNumber = 1,
  };
  // repeated .city.event.v2.Event events = 1;
  int events_size() const;
  private:
  int _internal_events_size() const;
  public:
  void clear_events();
  ::city::event::v2::Event* mutable_events(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::event::v2::Event >*
      mutable_events();
  private:
  const ::city::event::v2::Event& _internal_events(int index) const;
  ::city::event::v2::Event* _internal_add_events();
  public:
  const ::city::event::v2::Event& events(int index) const;
  ::city::event::v2::Event* add_events();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::event::v2::Event >&
      events() const;

  // @@protoc_insertion_point(class_scope:city.event.v2.ResolveEventsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::event::v2::Event > events_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_city_2fevent_2fv2_2fevent_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ResolveEventsResponse final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:city.event.v2.ResolveEventsResponse) */ {
 public:
  inline ResolveEventsResponse() : ResolveEventsResponse(nullptr) {}
  explicit PROTOBUF_CONSTEXPR ResolveEventsResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResolveEventsResponse(const ResolveEventsResponse& from);
  ResolveEventsResponse(ResolveEventsResponse&& from) noexcept
    : ResolveEventsResponse() {
    *this = ::std::move(from);
  }

  inline ResolveEventsResponse& operator=(const ResolveEventsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResolveEventsResponse& operator=(ResolveEventsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResolveEventsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResolveEventsResponse* internal_default_instance() {
    return reinterpret_cast<const ResolveEventsResponse*>(
               &_ResolveEventsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ResolveEventsResponse& a, ResolveEventsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ResolveEventsResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResolveEventsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResolveEventsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResolveEventsResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const ResolveEventsResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const ResolveEventsResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "city.event.v2.ResolveEventsResponse";
  }
  protected:
  explicit ResolveEventsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:city.event.v2.ResolveEventsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_city_2fevent_2fv2_2fevent_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetEventsByTopicRequest

// string topic = 1;
inline void GetEventsByTopicRequest::clear_topic() {
  _impl_.topic_.ClearToEmpty();
}
inline const std::string& GetEventsByTopicRequest::topic() const {
  // @@protoc_insertion_point(field_get:city.event.v2.GetEventsByTopicRequest.topic)
  return _internal_topic();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetEventsByTopicRequest::set_topic(ArgT0&& arg0, ArgT... args) {
 
 _impl_.topic_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:city.event.v2.GetEventsByTopicRequest.topic)
}
inline std::string* GetEventsByTopicRequest::mutable_topic() {
  std::string* _s = _internal_mutable_topic();
  // @@protoc_insertion_point(field_mutable:city.event.v2.GetEventsByTopicRequest.topic)
  return _s;
}
inline const std::string& GetEventsByTopicRequest::_internal_topic() const {
  return _impl_.topic_.Get();
}
inline void GetEventsByTopicRequest::_internal_set_topic(const std::string& value) {
  
  _impl_.topic_.Set(value, GetArenaForAllocation());
}
inline std::string* GetEventsByTopicRequest::_internal_mutable_topic() {
  
  return _impl_.topic_.Mutable(GetArenaForAllocation());
}
inline std::string* GetEventsByTopicRequest::release_topic() {
  // @@protoc_insertion_point(field_release:city.event.v2.GetEventsByTopicRequest.topic)
  return _impl_.topic_.Release();
}
inline void GetEventsByTopicRequest::set_allocated_topic(std::string* topic) {
  if (topic != nullptr) {
    
  } else {
    
  }
  _impl_.topic_.SetAllocated(topic, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.topic_.IsDefault()) {
    _impl_.topic_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:city.event.v2.GetEventsByTopicRequest.topic)
}

// -------------------------------------------------------------------

// GetEventsByTopicResponse

// repeated .city.event.v2.Event events = 1;
inline int GetEventsByTopicResponse::_internal_events_size() const {
  return _impl_.events_.size();
}
inline int GetEventsByTopicResponse::events_size() const {
  return _internal_events_size();
}
inline ::city::event::v2::Event* GetEventsByTopicResponse::mutable_events(int index) {
  // @@protoc_insertion_point(field_mutable:city.event.v2.GetEventsByTopicResponse.events)
  return _impl_.events_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::event::v2::Event >*
GetEventsByTopicResponse::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:city.event.v2.GetEventsByTopicResponse.events)
  return &_impl_.events_;
}
inline const ::city::event::v2::Event& GetEventsByTopicResponse::_internal_events(int index) const {
  return _impl_.events_.Get(index);
}
inline const ::city::event::v2::Event& GetEventsByTopicResponse::events(int index) const {
  // @@protoc_insertion_point(field_get:city.event.v2.GetEventsByTopicResponse.events)
  return _internal_events(index);
}
inline ::city::event::v2::Event* GetEventsByTopicResponse::_internal_add_events() {
  return _impl_.events_.Add();
}
inline ::city::event::v2::Event* GetEventsByTopicResponse::add_events() {
  ::city::event::v2::Event* _add = _internal_add_events();
  // @@protoc_insertion_point(field_add:city.event.v2.GetEventsByTopicResponse.events)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::event::v2::Event >&
GetEventsByTopicResponse::events() const {
  // @@protoc_insertion_point(field_list:city.event.v2.GetEventsByTopicResponse.events)
  return _impl_.events_;
}

// -------------------------------------------------------------------

// ResolveEventsRequest

// repeated .city.event.v2.Event events = 1;
inline int ResolveEventsRequest::_internal_events_size() const {
  return _impl_.events_.size();
}
inline int ResolveEventsRequest::events_size() const {
  return _internal_events_size();
}
inline ::city::event::v2::Event* ResolveEventsRequest::mutable_events(int index) {
  // @@protoc_insertion_point(field_mutable:city.event.v2.ResolveEventsRequest.events)
  return _impl_.events_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::event::v2::Event >*
ResolveEventsRequest::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:city.event.v2.ResolveEventsRequest.events)
  return &_impl_.events_;
}
inline const ::city::event::v2::Event& ResolveEventsRequest::_internal_events(int index) const {
  return _impl_.events_.Get(index);
}
inline const ::city::event::v2::Event& ResolveEventsRequest::events(int index) const {
  // @@protoc_insertion_point(field_get:city.event.v2.ResolveEventsRequest.events)
  return _internal_events(index);
}
inline ::city::event::v2::Event* ResolveEventsRequest::_internal_add_events() {
  return _impl_.events_.Add();
}
inline ::city::event::v2::Event* ResolveEventsRequest::add_events() {
  ::city::event::v2::Event* _add = _internal_add_events();
  // @@protoc_insertion_point(field_add:city.event.v2.ResolveEventsRequest.events)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::city::event::v2::Event >&
ResolveEventsRequest::events() const {
  // @@protoc_insertion_point(field_list:city.event.v2.ResolveEventsRequest.events)
  return _impl_.events_;
}

// -------------------------------------------------------------------

// ResolveEventsResponse

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v2
}  // namespace event
}  // namespace city

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_city_2fevent_2fv2_2fevent_5fservice_2eproto
